services:
    type: web
    name: kilimo-backend
    env: python
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GEMINI_API_KEY
        sync: false
